-- * ダミーデータの挿入 */

-- /* t_category */
-- INSERT INTO t_category (category_name) VALUES ('お手伝い');
-- INSERT INTO t_category (category_name) VALUES ('勉強');
-- INSERT INTO t_category (category_name) VALUES ('運動');
-- INSERT INTO t_category (category_name) VALUES ('遊び');
-- /* t_role */
-- INSERT INTO t_role (role_name) VALUES ('子供');
-- INSERT INTO t_role (role_name) VALUES ('母');
-- INSERT INTO t_role (role_name) VALUES ('父');

-- /* t_user */
-- INSERT INTO t_user (name, password, role_id) VALUES ('me1002', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('wk0128', 'password', 3);
-- INSERT INTO t_user (name, password, role_id) VALUES ('am1210', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('nt1029', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('yh1020', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('oj0622', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('fj0809', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('am0407', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('hr0617', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('ss1106', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('ky0722', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('mt0603', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('oa1024', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('tuboi', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('tanabe', 'password', 1);

-- INSERT INTO t_user (name, password, role_id) VALUES ('guest1', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest2', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest3', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest4', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest5', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest6', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest7', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest8', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest9', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest10', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest11', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest12', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest13', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest14', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest15', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest16', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest17', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest18', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest19', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest20', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest21', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest22', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest23', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest24', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest25', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest26', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest27', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest28', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest29', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest30', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest31', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest32', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest33', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest34', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest35', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest36', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest37', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest38', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest39', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest40', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest41', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest42', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest43', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest44', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest45', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest46', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest47', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest48', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest49', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest50', 'password', 1);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest51', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest52', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest53', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest54', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest55', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest56', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest57', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest58', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest59', 'password', 2);
-- INSERT INTO t_user (name, password, role_id) VALUES ('guest60', 'password', 2);


-- /* t_card */
-- INSERT INTO t_card (user_id, card_title, centerMission, start_date, end_date) VALUES (1, '夏休みカード','image/こらしょ.png', '2021-07-27', '2021-08-27');

-- /* t_mission */
-- INSERT INTO t_mission (card_id, mission_place, goal_id, done, created_date) VALUES (1, 1, 1, false, '2021-07-27');
-- INSERT INTO t_mission (card_id, mission_place, goal_id, done, created_date) VALUES (1, 2, 2, false, '2021-07-17');
-- INSERT INTO t_mission (card_id, mission_place, goal_id, done, created_date) VALUES (1, 3, 3, false, '2021-07-27');
-- INSERT INTO t_mission (card_id, mission_place, goal_id, done, created_date) VALUES (1, 4, 4, false, '2021-07-27');
-- INSERT INTO t_mission (card_id, mission_place, goal_id, done, created_date) VALUES (1, 5, 5, false, '2021-07-27');
-- INSERT INTO t_mission (card_id, mission_place, goal_id, done, created_date) VALUES (1, 6, 42, false, '2021-07-27');
